#!/bin/sh
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
for dir in colors commander ez-mongodb ez-streams galaxy jsurl regenerator source-map \
	streamline streamline-doctool streamline-flamegraph streamline-fs \
	streamline-pdfkit streamline-plugin streamline-require streamline-runtime; do
		echo "clearing " $dir
		rm -rf $DIR/node_modules/$dir/* $DIR/node_modules/$dir/.[a-z]*
done;
