?Select
BPC.BPCNAM_0 As BPC_BPCNAM
,BPC.BPCSHO_0 As BPC_BPCSHO
,BPC.BPAINV_0 As BPC_BPAINV
,BPC.BPAPYR_0 As BPC_BPAPYR
,BPC.BPAADD_0 As BPC_BPAADD
,BPC.BPDADD_0 As BPC_BPDADD
,BPC.CNTNAM_0 As BPC_CNTNAM
,BPC.BPCBPSNUM_0 As BPC_BPCBPSNUM
,BPC.VATEXN_0 As BPC_VATEXN
,BPC.BPCREM_0 As BPC_BPCREM
,BPC.ORDTEX_0 As BPC_ORDTEX
,BPC.INVTEX_0 As BPC_INVTEX
,BPC.CREUSR_0 As BPC_CREUSR
,BPC.UPDUSR_0 As BPC_UPDUSR
,BPC.BPCNUM_0 As BPC_BPCNUM
,BPR.BPRNAM_0 As BPR_BPRNAM
,BPR.BPRSHO_0 As BPR_BPRSHO
,BPR.EECNUM_0 As BPR_EECNUM
,BPR.CRN_0 As BPR_CRN
,BPR.NAF_0 As BPR_NAF
,BPR.BPRLOG_0 As BPR_BPRLOG
,BPR.VATNUM_0 As BPR_VATNUM
,BPR.FISCOD_0 As BPR_FISCOD
,BPR.GRUGPY_0 As BPR_GRUGPY
,BPR.GRUCOD_0 As BPR_GRUCOD
,BPR.BPAADD_0 As BPR_BPAADD
,BPR.CNTNAM_0 As BPR_CNTNAM
,BPR.BIDNUM_0 As BPR_BIDNUM
,BPR.ACCNONREI_0 As BPR_ACCNONREI
,BPR.CREUSR_0 As BPR_CREUSR
,BPR.UPDUSR_0 As BPR_UPDUSR
,A_XX1.TEXTE_0 As BCG_1_DESAXX_FRA
,A_XX2.TEXTE_0 As BCG_1_DESAXX_ENG
,A_XX3.TEXTE_0 As BCG_1_DESAXX_POR
,A_XX4.TEXTE_0 As TCY_2_CRYDES_FRA
,A_XX5.TEXTE_0 As TCY_2_CRYDES_ENG
,A_XX6.TEXTE_0 As TCY_2_CRYDES_POR
,A_XX7.TEXTE_0 As TCU_3_INTDES_FRA
,A_XX8.TEXTE_0 As TCU_3_INTDES_ENG
,A_XX9.TEXTE_0 As TCU_3_INTDES_POR
,BPR_4.BPRNAM_0 As BPR_4_BPRNAM
,BPR_5.BPRNAM_0 As BPR_5_BPRNAM
,BPR_6.BPRNAM_0 As BPR_6_BPRNAM
,BPR_7.BPRNAM_0 As BPR_7_BPRNAM
,BPC.TSCCOD_0 As BPC_TSCCOD
,A_XX10.TEXTE_0 As BPC_TSCCOD_TEXTE_FRA
,A_XX11.TEXTE_0 As BPC_TSCCOD_TEXTE_ENG
,A_XX12.TEXTE_0 As BPC_TSCCOD_TEXTE_POR
,A_XX13.TEXTE_0 As TPT_8_DESAXX_FRA
,A_XX14.TEXTE_0 As TPT_8_DESAXX_ENG
,A_XX15.TEXTE_0 As TPT_8_DESAXX_POR
,A_XX16.TEXTE_0 As TDA_9_DESAXX_FRA
,A_XX17.TEXTE_0 As TDA_9_DESAXX_ENG
,A_XX18.TEXTE_0 As TDA_9_DESAXX_POR
,BPC.VACBPR_0 As BPC_VACBPR
,A_XX19.TEXTE_0 As BPC_VACBPR_TEXTE_FRA
,A_XX20.TEXTE_0 As BPC_VACBPR_TEXTE_ENG
,A_XX21.TEXTE_0 As BPC_VACBPR_TEXTE_POR
,A_ML1.LANMES_0 As BPR_LEGETT_MESS_FRA
,A_ML2.LANMES_0 As BPR_LEGETT_MESS_ENG
,A_ML3.LANMES_0 As BPR_LEGETT_MESS_POR
,A_ML4.LANMES_0 As BPC_BPCSTA_MESS_FRA
,A_ML5.LANMES_0 As BPC_BPCSTA_MESS_ENG
,A_ML6.LANMES_0 As BPC_BPCSTA_MESS_POR
,'DEMO' as BPCIND_AX3DOSSIER
,'SOLX3V62' as BPCIND_AX3SOLUTION
,'BPCIND' as BPCIND_AX3MODELE
,'X3VM62' as BPCIND_AX3SERVEUR
,'openX3({''solution'':''SOLX3V62'',''folder'':''DEMO'',''object'':''BPC'',''key'':'''||BPC.BPCNUM_0||'''})~' as BPCIND_X3LINK
,'Clients : '||BPC.BPCNAM_0||'('||BPC.BPCNUM_0||')~' As BPCIND_X3TITLE_FRA
,'Clients' as BPCIND_AX3MODELE_FRA
,'Customers : '||BPC.BPCNAM_0||'('||BPC.BPCNUM_0||')~' As BPCIND_X3TITLE_ENG
,'Customers' as BPCIND_AX3MODELE_ENG
,'Clientes : '||BPC.BPCNAM_0||'('||BPC.BPCNUM_0||')~' As BPCIND_X3TITLE_POR
,'Clientes' as BPCIND_AX3MODELE_POR
From
 BPCUSTOMER BPC 
 INNER JOIN BPARTNER BPR ON (BPR.BPRNUM_0 = BPC.BPCNUM_0) 
 LEFT OUTER JOIN BPCCATEG BCG_1 ON (BCG_1.BCGCOD_0 = BPC.BCGCOD_0) 
 LEFT OUTER JOIN TABCOUNTRY TCY_2 ON (TCY_2.CRY_0 = BPR.CRY_0) 
 LEFT OUTER JOIN TABCUR TCU_3 ON (TCU_3.CUR_0 = BPR.CUR_0) 
 LEFT OUTER JOIN BPARTNER BPR_4 ON (BPR_4.BPRNUM_0 = BPC.BPCINV_0) 
 LEFT OUTER JOIN BPARTNER BPR_5 ON (BPR_5.BPRNUM_0 = BPC.BPCPYR_0) 
 LEFT OUTER JOIN BPARTNER BPR_6 ON (BPR_6.BPRNUM_0 = BPC.BPCGRU_0) 
 LEFT OUTER JOIN BPARTNER BPR_7 ON (BPR_7.BPRNUM_0 = BPC.BPCRSK_0) 
 LEFT OUTER JOIN TABPAYTERM TPT_8 ON (TPT_8.PTE_0 = BPC.PTE_0 AND TPT_8.PTELIN_0 = 1) 
 LEFT OUTER JOIN TABDEPAGIO TDA_9 ON (TDA_9.DEP_0 = BPC.DEP_0) 
 LEFT OUTER JOIN ATEXTRA A_XX1 ON ( A_XX1.CODFIC_0='BPCCATEG' AND A_XX1.ZONE_0  ='DESAXX' AND A_XX1.IDENT1_0=BCG_1.BCGCOD_0 AND A_XX1.IDENT2_0=' ' AND A_XX1.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX2 ON ( A_XX2.CODFIC_0='BPCCATEG' AND A_XX2.ZONE_0  ='DESAXX' AND A_XX2.IDENT1_0=BCG_1.BCGCOD_0 AND A_XX2.IDENT2_0=' ' AND A_XX2.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX3 ON ( A_XX3.CODFIC_0='BPCCATEG' AND A_XX3.ZONE_0  ='DESAXX' AND A_XX3.IDENT1_0=BCG_1.BCGCOD_0 AND A_XX3.IDENT2_0=' ' AND A_XX3.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX4 ON ( A_XX4.CODFIC_0='TABCOUNTRY' AND A_XX4.ZONE_0  ='CRYDES' AND A_XX4.IDENT1_0=TCY_2.CRY_0 AND A_XX4.IDENT2_0=' ' AND A_XX4.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX5 ON ( A_XX5.CODFIC_0='TABCOUNTRY' AND A_XX5.ZONE_0  ='CRYDES' AND A_XX5.IDENT1_0=TCY_2.CRY_0 AND A_XX5.IDENT2_0=' ' AND A_XX5.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX6 ON ( A_XX6.CODFIC_0='TABCOUNTRY' AND A_XX6.ZONE_0  ='CRYDES' AND A_XX6.IDENT1_0=TCY_2.CRY_0 AND A_XX6.IDENT2_0=' ' AND A_XX6.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX7 ON ( A_XX7.CODFIC_0='TABCUR' AND A_XX7.ZONE_0  ='INTDES' AND A_XX7.IDENT1_0=TCU_3.CUR_0 AND A_XX7.IDENT2_0=' ' AND A_XX7.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX8 ON ( A_XX8.CODFIC_0='TABCUR' AND A_XX8.ZONE_0  ='INTDES' AND A_XX8.IDENT1_0=TCU_3.CUR_0 AND A_XX8.IDENT2_0=' ' AND A_XX8.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX9 ON ( A_XX9.CODFIC_0='TABCUR' AND A_XX9.ZONE_0  ='INTDES' AND A_XX9.IDENT1_0=TCU_3.CUR_0 AND A_XX9.IDENT2_0=' ' AND A_XX9.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX10 ON ( A_XX10.CODFIC_0='ATABDIV' AND A_XX10.ZONE_0  ='LNGDES' AND A_XX10.IDENT1_0='30' AND A_XX10.IDENT2_0=BPC.TSCCOD_0 AND A_XX10.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX11 ON ( A_XX11.CODFIC_0='ATABDIV' AND A_XX11.ZONE_0  ='LNGDES' AND A_XX11.IDENT1_0='30' AND A_XX11.IDENT2_0=BPC.TSCCOD_0 AND A_XX11.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX12 ON ( A_XX12.CODFIC_0='ATABDIV' AND A_XX12.ZONE_0  ='LNGDES' AND A_XX12.IDENT1_0='30' AND A_XX12.IDENT2_0=BPC.TSCCOD_0 AND A_XX12.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX13 ON ( A_XX13.CODFIC_0='TABPAYTERM' AND A_XX13.ZONE_0  ='DESAXX' AND A_XX13.IDENT1_0=TPT_8.PTE_0 AND A_XX13.IDENT2_0=' ' AND A_XX13.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX14 ON ( A_XX14.CODFIC_0='TABPAYTERM' AND A_XX14.ZONE_0  ='DESAXX' AND A_XX14.IDENT1_0=TPT_8.PTE_0 AND A_XX14.IDENT2_0=' ' AND A_XX14.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX15 ON ( A_XX15.CODFIC_0='TABPAYTERM' AND A_XX15.ZONE_0  ='DESAXX' AND A_XX15.IDENT1_0=TPT_8.PTE_0 AND A_XX15.IDENT2_0=' ' AND A_XX15.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX16 ON ( A_XX16.CODFIC_0='TABDEPAGIO' AND A_XX16.ZONE_0  ='DESAXX' AND A_XX16.IDENT1_0=TDA_9.DEP_0 AND A_XX16.IDENT2_0=' ' AND A_XX16.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX17 ON ( A_XX17.CODFIC_0='TABDEPAGIO' AND A_XX17.ZONE_0  ='DESAXX' AND A_XX17.IDENT1_0=TDA_9.DEP_0 AND A_XX17.IDENT2_0=' ' AND A_XX17.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX18 ON ( A_XX18.CODFIC_0='TABDEPAGIO' AND A_XX18.ZONE_0  ='DESAXX' AND A_XX18.IDENT1_0=TDA_9.DEP_0 AND A_XX18.IDENT2_0=' ' AND A_XX18.LANGUE_0='POR') 
 LEFT OUTER JOIN ATEXTRA A_XX19 ON ( A_XX19.CODFIC_0='ATABDIV' AND A_XX19.ZONE_0  ='LNGDES' AND A_XX19.IDENT1_0='1' AND A_XX19.IDENT2_0=BPC.VACBPR_0 AND A_XX19.LANGUE_0='FRA') 
 LEFT OUTER JOIN ATEXTRA A_XX20 ON ( A_XX20.CODFIC_0='ATABDIV' AND A_XX20.ZONE_0  ='LNGDES' AND A_XX20.IDENT1_0='1' AND A_XX20.IDENT2_0=BPC.VACBPR_0 AND A_XX20.LANGUE_0='ENG') 
 LEFT OUTER JOIN ATEXTRA A_XX21 ON ( A_XX21.CODFIC_0='ATABDIV' AND A_XX21.ZONE_0  ='LNGDES' AND A_XX21.IDENT1_0='1' AND A_XX21.IDENT2_0=BPC.VACBPR_0 AND A_XX21.LANGUE_0='POR') 
 LEFT OUTER JOIN APLSTD A_ML1 ON ( A_ML1.LANNUM_0=BPR.LEGETT_0 AND A_ML1.LANCHP_0=1 AND A_ML1.LAN_0='FRA'AND A_ML1.LANNUM_0>0) 
 LEFT OUTER JOIN APLSTD A_ML2 ON ( A_ML2.LANNUM_0=BPR.LEGETT_0 AND A_ML2.LANCHP_0=1 AND A_ML2.LAN_0='ENG'AND A_ML2.LANNUM_0>0) 
 LEFT OUTER JOIN APLSTD A_ML3 ON ( A_ML3.LANNUM_0=BPR.LEGETT_0 AND A_ML3.LANCHP_0=1 AND A_ML3.LAN_0='POR'AND A_ML3.LANNUM_0>0) 
 LEFT OUTER JOIN APLSTD A_ML4 ON ( A_ML4.LANNUM_0=BPC.BPCSTA_0 AND A_ML4.LANCHP_0=1 AND A_ML4.LAN_0='FRA'AND A_ML4.LANNUM_0>0) 
 LEFT OUTER JOIN APLSTD A_ML5 ON ( A_ML5.LANNUM_0=BPC.BPCSTA_0 AND A_ML5.LANCHP_0=1 AND A_ML5.LAN_0='ENG'AND A_ML5.LANNUM_0>0) 
 LEFT OUTER JOIN APLSTD A_ML6 ON ( A_ML6.LANNUM_0=BPC.BPCSTA_0 AND A_ML6.LANCHP_0=1 AND A_ML6.LAN_0='POR'AND A_ML6.LANNUM_0>0) 
 Where 1=1 
