Select
BPC.UUID,
BPC.BPCNAM_0 As BPC_BPCNAM
,BPC.BPCSHO_0 As BPC_BPCSHO
,BPC.CNTNAM_0 As BPC_CNTNAM
,BPC.BPCBPSNUM_0 As BPC_BPCBPSNUM
,BPC.VATEXN_0 As BPC_VATEXN
,BPC.BPCREM_0 As BPC_BPCREM
,BPC.ORDTEX_0 As BPC_ORDTEX
,BPC.INVTEX_0 As BPC_INVTEX
,BPC.CREUSR_0 As BPC_CREUSR
,BPC.UPDUSR_0 As BPC_UPDUSR
,BPC.BPCNUM_0 As BPC_BPCNUM
--
,bpainv.bpades_0
,bpainv.bpaaddlig_0
,bpainv.bpaaddlig_1
,bpainv.bpaaddlig_2
,bpainv.poscod_0
,bpainv.cty_0
,bpainv.cry_0
,bpainv.crynam_0
--
,BPR.BPRNAM_0 As BPR_BPRNAM
,BPR.BPRSHO_0 As BPR_BPRSHO
,BPR.EECNUM_0 As BPR_EECNUM
,BPR.CRN_0 As BPR_CRN
,BPR.NAF_0 As BPR_NAF
,BPR.BPRLOG_0 As BPR_BPRLOG
,BPR.VATNUM_0 As BPR_VATNUM
,BPR.FISCOD_0 As BPR_FISCOD
,BPR.GRUGPY_0 As BPR_GRUGPY
,BPR.GRUCOD_0 As BPR_GRUCOD
,BPR.BPAADD_0 As BPR_BPAADD
,BPR.CNTNAM_0 As BPR_CNTNAM
,BPR.BIDNUM_0 As BPR_BIDNUM
,BPR.ACCNONREI_0 As BPR_ACCNONREI
,BPR.CREUSR_0 As BPR_CREUSR
,BPR.UPDUSR_0 As BPR_UPDUSR
From
BPCUSTOMER BPC
join BPARTNER BPR on (BPR.BPRNUM_0=BPC.BPCNUM_0)
left outer join BPADDRESS BPAINV on (BPC.BPCNUM_0=BPAINV.BPANUM_0) and (BPC.BPAADD_0=bpainv.bpaadd_0)
