FROM node:4.2

# oracle instantclient
RUN curl -SL http://192.168.99.1/instantclient-basiclite-linux.x64-12.1.0.2.0.tar.xz | tar -xoJC /runtime && \
    curl -SL http://192.168.99.1/instantclient-sqlplus-linux.x64-12.1.0.2.0.tar.xz | tar -xoJC /runtime && \
    ln -s /runtime/instantclient_12_1 /runtime/instantclient_12_1/bin && \
    ln -s /runtime/instantclient_12_1 /runtime/instantclient_12_1/lib && \
    chown -R nobody:nogroup /runtime/instantclient_12_1 && \
    chmod -R 775 /runtime/instantclient_12_1 

RUN mkdir -p /syracuse
RUN mkdir -p /config
RUN mkdir -p /extensions

WORKDIR /syracuse

COPY syracuse .

RUN cp /syracuse/docker/nodelocal-syr-etna.docker /syracuse/nodelocal.js

RUN cd /syracuse

VOLUME /config
VOLUME /extensions
EXPOSE 8124

CMD node .