FROM busybox

RUN mkdir -p /config /extensions /config/devLic

COPY devLic/ /config/devLic
COPY artefacts/scm/nodelocal-syr-etna.docker /config/nodelocal.js
COPY artefacts/scm/scm-initialization-x3/ /extensions/scm-initialization/

VOLUME /config
VOLUME /extensions

CMD tail -f /dev/null