//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.586
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sage X3 for Office ähnelt.
        /// </summary>
        internal static string AddinTitle {
            get {
                return ResourceManager.GetString("AddinTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot create a table with {0} columns and {1} rows. Please check your insert preferences.{3}(Error was: &quot;{2}&quot;) ähnelt.
        /// </summary>
        internal static string CreateTableError {
            get {
                return ResourceManager.GetString("CreateTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot shift up {0} columns and {1} rows. The range value are cleared.{3}(Error was: &quot;{2}&quot;) ähnelt.
        /// </summary>
        internal static string DeleteCellsError {
            get {
                return ResourceManager.GetString("DeleteCellsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot shift down {0} columns and {1} rows, the range might overlap another table. Please check your insert preferences.{3}(Error was: &quot;{2}&quot;) ähnelt.
        /// </summary>
        internal static string InsertCellsError {
            get {
                return ResourceManager.GetString("InsertCellsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot insert {0} rows, the range might overlap another table. Please check your insert preferences.{2}(Error was: &quot;{1}&quot;) ähnelt.
        /// </summary>
        internal static string InsertRowsError {
            get {
                return ResourceManager.GetString("InsertRowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Addin available. Do do want to install it? ähnelt.
        /// </summary>
        internal static string MSG_NEW_VERSION {
            get {
                return ResourceManager.GetString("MSG_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install new version? ähnelt.
        /// </summary>
        internal static string MSG_NEW_VERSION_TITLE {
            get {
                return ResourceManager.GetString("MSG_NEW_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please restart your Excel after the installation of the new Addin. ähnelt.
        /// </summary>
        internal static string MSG_RESTART {
            get {
                return ResourceManager.GetString("MSG_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart Excel ähnelt.
        /// </summary>
        internal static string MSG_RESTART_TITLE {
            get {
                return ResourceManager.GetString("MSG_RESTART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This workbook is published on X3, it will be saved on X3. If You want to save a copy of it, please use &quot;Save as&quot; feature. 
        ///Do You want to proceed with Save? ähnelt.
        /// </summary>
        internal static string MSG_SAVE_AS {
            get {
                return ResourceManager.GetString("MSG_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save workbook ähnelt.
        /// </summary>
        internal static string MSG_SAVE_AS_TITLE {
            get {
                return ResourceManager.GetString("MSG_SAVE_AS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The reference &quot;{0}&quot; is allready associated with table &quot;{1}&quot;. Do You want to delete table &quot;{1}&quot; and replace its content ? ähnelt.
        /// </summary>
        internal static string OverrideTableConfirm {
            get {
                return ResourceManager.GetString("OverrideTableConfirm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot resize a table with {0} columns and {1} rows. Please check Your insert preferences.\n (Error was: &quot;{2}&quot;) ähnelt.
        /// </summary>
        internal static string ResizeTableError {
            get {
                return ResourceManager.GetString("ResizeTableError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_settings {
            get {
                object obj = ResourceManager.GetObject("server_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
