//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonDialogs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User details ähnelt.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_GROUPBOX {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_GROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sage ERP X3 - Credentials ähnelt.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User name ähnelt.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_USER_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_USER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_DESCRIPTION_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_DESCRIPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publish Document ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_DIALOG_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_DIALOG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publication details ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_GROUPBOX {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_GROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_OWNER_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_OWNER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read-only ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_READONLY_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_READONLY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage volume ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_STORAGE_VOLUME_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_STORAGE_VOLUME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publish Mail merge template ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_TEMPLATE_MAIL_MERGE {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_TEMPLATE_MAIL_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publish report template ähnelt.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_TEMPLATE_REPORT {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_TEMPLATE_REPORT", resourceCulture);
            }
        }
    }
}
