//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonDialogs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_GROUPBOX {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_GROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage ERP X3 - Credentials.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string CREDENTIALS_DIALOG_USER_LABEL {
            get {
                return ResourceManager.GetString("CREDENTIALS_DIALOG_USER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_DESCRIPTION_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_DESCRIPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Document.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_DIALOG_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_DIALOG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication details.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_GROUPBOX {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_GROUPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_OWNER_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_OWNER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_READONLY_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_READONLY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage volume.
        /// </summary>
        internal static string PUBLISH_DOCUMENT_STORAGE_VOLUME_LABEL {
            get {
                return ResourceManager.GetString("PUBLISH_DOCUMENT_STORAGE_VOLUME_LABEL", resourceCulture);
            }
        }
    }
}
